--- # copying a file
- hosts: all
  become: yes
  user: ansible
  connection: ssh
  tasks:
    - name: copying a file
      copy:
        src: /home/ansible/playbooks/index.html
        dest: /home/ansible

