--- # Install java & tomcat in playbook
- hosts: all
  become: yes
  tasks:
    - name: install java s/w in redhat
      action: yum name=java state=present
      when: ansible_os_family == "RedHat"
    - name: install java s/w in debian
      action: apt name=default-jdk state=present
      when: ansible_os_family == "Debian"
    - name: download tomcat s/w in playbook
      get_url:
          url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.79/bin/apache-tomcat-8.5.79.tar.gz
          dest: /opt
    - name: extract tar.zip for tomcat url
      unarchive: 
         src: /opt/apache-tomcat-8.5.79.tar.gz
         dest: /opt
         remote_src: yes
    - name: providing executable permissions
      file: 
        path: /opt/apache-tomcat-8.5.79/bin/startup.sh
        mode: 0777
    - name: executing sh shell script file
      shell: nohup ./startup.sh
      args:
        chdir: /opt/apache-tomcat-8.5.79/bin

